/*
SendPost API

Testing StatsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sendpost

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sendpost/sendpost-go-sdk"
)

func Test_sendpost_StatsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StatsAPIService AccountSubaccountStatSubaccountIdAggregateGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var subaccountId int64

		resp, httpRes, err := apiClient.StatsAPI.AccountSubaccountStatSubaccountIdAggregateGet(context.Background(), subaccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StatsAPIService AccountSubaccountStatSubaccountIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var subaccountId int64

		resp, httpRes, err := apiClient.StatsAPI.AccountSubaccountStatSubaccountIdGet(context.Background(), subaccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StatsAPIService GetAggregateStatsByGroup", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var subaccountId int64

		resp, httpRes, err := apiClient.StatsAPI.GetAggregateStatsByGroup(context.Background(), subaccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
