/*
SendPost API

Testing WebhookReferenceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sendpost

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sendpost/sendpost-go-sdk"
)

func Test_sendpost_WebhookReferenceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WebhookReferenceAPIService SendPostWebhooksPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.WebhookReferenceAPI.SendPostWebhooksPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
