/*
SendPost API

Testing IPPoolsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sendpost

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sendpost/sendpost-go-sdk"
)

func Test_sendpost_IPPoolsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IPPoolsAPIService CreateIPPool", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IPPoolsAPI.CreateIPPool(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPPoolsAPIService DeleteIPPool", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ippoolId int32

		resp, httpRes, err := apiClient.IPPoolsAPI.DeleteIPPool(context.Background(), ippoolId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPPoolsAPIService GetAllIPPools", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IPPoolsAPI.GetAllIPPools(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPPoolsAPIService GetIPPoolById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ippoolId int32

		resp, httpRes, err := apiClient.IPPoolsAPI.GetIPPoolById(context.Background(), ippoolId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPPoolsAPIService UpdateIPPool", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ippoolId int32

		resp, httpRes, err := apiClient.IPPoolsAPI.UpdateIPPool(context.Background(), ippoolId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
