/*
SendPost API

Testing DomainAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sendpost

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sendpost/sendpost-go-sdk"
)

func Test_sendpost_DomainAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DomainAPIService GetAllDomains", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DomainAPI.GetAllDomains(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DomainAPIService SubaccountDomainDomainIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domainId string

		resp, httpRes, err := apiClient.DomainAPI.SubaccountDomainDomainIdDelete(context.Background(), domainId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DomainAPIService SubaccountDomainDomainIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var domainId string

		resp, httpRes, err := apiClient.DomainAPI.SubaccountDomainDomainIdGet(context.Background(), domainId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DomainAPIService SubaccountDomainPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DomainAPI.SubaccountDomainPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
