/*
SendPost API

Testing SubAccountAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sendpost

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sendpost/sendpost-go-sdk"
)

func Test_sendpost_SubAccountAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SubAccountAPIService CreateSubAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SubAccountAPI.CreateSubAccount(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubAccountAPIService DeleteSubAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var subaccountId int32

		resp, httpRes, err := apiClient.SubAccountAPI.DeleteSubAccount(context.Background(), subaccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubAccountAPIService GetAllSubAccounts", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SubAccountAPI.GetAllSubAccounts(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubAccountAPIService GetSubAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var subaccountId int32

		resp, httpRes, err := apiClient.SubAccountAPI.GetSubAccount(context.Background(), subaccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubAccountAPIService UpdateSubAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var subaccountId int32

		resp, httpRes, err := apiClient.SubAccountAPI.UpdateSubAccount(context.Background(), subaccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
