/*
SendPost API

Testing IPAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sendpost

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sendpost/sendpost-go-sdk"
)

func Test_sendpost_IPAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IPAPIService AllocateNewIp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IPAPI.AllocateNewIp(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPAPIService DeleteIp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ipId int32

		resp, httpRes, err := apiClient.IPAPI.DeleteIp(context.Background(), ipId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPAPIService GetAllIps", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IPAPI.GetAllIps(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPAPIService GetSpecificIp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ipId int32

		resp, httpRes, err := apiClient.IPAPI.GetSpecificIp(context.Background(), ipId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPAPIService UpdateIp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ipId int32

		resp, httpRes, err := apiClient.IPAPI.UpdateIp(context.Background(), ipId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
